// auth-config.js

const SUPABASE_URL = 'https://zteetrqjvkgzkquyhocj.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0ZWV0cnFqdmtnemtxdXlob2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzcxMTEsImV4cCI6MjA2NTI1MzExMX0.Qn--GbpQQMphZo5s4V3spodRAqvjc2xFVrwhfRkrY6M';